import datetime
from backend.database.database import SessionLocal
from backend.models.india_project import IndiaProject


VERIFIED_AT = datetime.datetime(2026, 9, 17)


INDIA_PROJECTS = [
    {
        "name": "Noida International Airport",
        "category": "Airport",
        "location": "Jewar, Uttar Pradesh",
        "status": "Operational",
        "description": "International airport project serving the Delhi-NCR region, with official operator updates covering the start of commercial operations.",
        "key_facts": ["Delhi-NCR aviation infrastructure", "Jewar, Uttar Pradesh"],
        "official_source_url": "https://www.niairport.in/en/company/news/2026/2026-06-15",
        "source_note": "Status reviewed against the airport operator's official 2026 operations update.",
        "tags": ["airport", "uttar-pradesh", "delhi-ncr"],
    },
    {
        "name": "Navi Mumbai International Airport",
        "category": "Airport",
        "location": "Navi Mumbai, Maharashtra",
        "status": "Development / commissioning",
        "description": "Large-scale airport development serving the Mumbai Metropolitan Region.",
        "key_facts": ["Mumbai Metropolitan Region", "Maharashtra aviation infrastructure"],
        "official_source_url": "https://navimumbai.adaniairports.com/",
        "source_note": "Official airport operator source; commissioning status should be rechecked as the project progresses.",
        "tags": ["airport", "maharashtra"],
    },
    {
        "name": "Vadhavan Port",
        "category": "Port",
        "location": "Palghar, Maharashtra",
        "status": "Under development",
        "description": "Deep-draft port project identified in official Government of India infrastructure updates.",
        "key_facts": ["Palghar district", "Maharashtra maritime infrastructure"],
        "official_source_url": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2294245",
        "source_note": "Status reviewed against an official Press Information Bureau update on Maharashtra port development.",
        "tags": ["port", "maharashtra", "maritime"],
    },
    {
        "name": "National Maritime Heritage Complex",
        "category": "Museum",
        "location": "Lothal, Gujarat",
        "status": "Under construction",
        "description": "Maritime heritage and museum complex at the historic Lothal site.",
        "key_facts": ["Lothal heritage site", "Maritime history and museum campus"],
        "official_source_url": "https://nmhc.in/",
        "source_note": "Official National Maritime Heritage Complex source.",
        "tags": ["museum", "gujarat", "heritage"],
    },
    {
        "name": "Chenab Railway Bridge",
        "category": "Bridge",
        "location": "Jammu and Kashmir",
        "status": "Completed / operational",
        "description": "Major railway arch bridge on the Udhampur–Srinagar–Baramulla Rail Link.",
        "key_facts": ["Railway bridge", "Jammu and Kashmir connectivity"],
        "official_source_url": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2134513",
        "source_note": "Status reviewed against the official inauguration release.",
        "tags": ["bridge", "rail", "jammu-and-kashmir"],
    },
    {
        "name": "Mumbai Trans Harbour Link (Atal Setu)",
        "category": "Bridge",
        "location": "Mumbai–Navi Mumbai, Maharashtra",
        "status": "Completed / operational",
        "description": "Sea bridge connecting Mumbai and Navi Mumbai across Mumbai Harbour.",
        "key_facts": ["Mumbai Harbour crossing", "Mumbai Metropolitan Region"],
        "official_source_url": "https://mmrda.maharashtra.gov.in/",
        "source_note": "Official Mumbai Metropolitan Region Development Authority source.",
        "tags": ["bridge", "maharashtra", "mumbai"],
    },
    {
        "name": "Sudarshan Setu",
        "category": "Bridge",
        "location": "Okha–Beyt Dwarka, Gujarat",
        "status": "Completed / operational",
        "description": "Signature cable-stayed bridge improving access to Beyt Dwarka.",
        "key_facts": ["Gujarat coastal connectivity", "Okha–Beyt Dwarka link"],
        "official_source_url": "https://www.gujarattourism.com/",
        "source_note": "Official Gujarat government tourism source; project status is presented without operational performance claims.",
        "tags": ["bridge", "gujarat", "coastal-connectivity"],
    },
    {
        "name": "Zoji La Tunnel",
        "category": "Tunnel",
        "location": "Jammu and Kashmir–Ladakh",
        "status": "Under construction",
        "description": "Strategic all-weather road tunnel project on the Srinagar–Leh corridor.",
        "key_facts": ["Srinagar–Leh corridor", "All-weather connectivity"],
        "official_source_url": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1995649",
        "source_note": "Status reviewed against an official Press Information Bureau infrastructure release.",
        "tags": ["tunnel", "ladakh", "jammu-and-kashmir"],
    },
    {
        "name": "Mumbai–Ahmedabad Bullet Train",
        "category": "Rail",
        "location": "Maharashtra–Gujarat",
        "status": "Under construction",
        "description": "High-speed rail corridor being delivered by the National High Speed Rail Corporation Limited.",
        "key_facts": ["Mumbai–Ahmedabad corridor", "High-speed rail"],
        "official_source_url": "https://nhsrcl.in/en/home",
        "source_note": "Official NHSRCL source; no fabricated completion or progress figures are shown.",
        "tags": ["rail", "maharashtra", "gujarat", "high-speed-rail"],
    },
    {
        "name": "Delhi–Meerut RRTS",
        "category": "RRTS",
        "location": "Delhi–Uttar Pradesh",
        "status": "Operational",
        "description": "Regional rapid transit corridor connecting Delhi with Meerut.",
        "key_facts": ["Delhi–Meerut corridor", "Regional rapid transit"],
        "official_source_url": "https://ncrtc.in/",
        "source_note": "Official NCRTC source.",
        "tags": ["rrts", "rail", "delhi", "uttar-pradesh"],
    },
    {
        "name": "Delhi–Panipat–Karnal RRTS",
        "category": "RRTS",
        "location": "Delhi–Haryana",
        "status": "Development",
        "description": "Proposed regional rapid transit connection between Delhi and the Panipat–Karnal region.",
        "key_facts": ["Delhi–Haryana corridor", "Regional rapid transit planning"],
        "official_source_url": "https://ncrtc.in/",
        "source_note": "Official NCRTC source; the project is shown as a development-stage corridor without invented schedule claims.",
        "tags": ["rrts", "rail", "delhi", "haryana"],
    },
    {
        "name": "Delhi–Mumbai Expressway",
        "category": "Highway",
        "location": "Multiple states",
        "status": "Phased development",
        "description": "National highway corridor connecting the Delhi and Mumbai regions through multiple construction packages.",
        "key_facts": ["Multi-state highway corridor", "Phased package delivery"],
        "official_source_url": "https://nhai.gov.in/",
        "source_note": "Official National Highways Authority of India source.",
        "tags": ["highway", "multi-state", "nhai"],
    },
    {
        "name": "Thane Coastal Road",
        "category": "Coastal Road",
        "location": "Thane, Maharashtra",
        "status": "Under construction",
        "description": "Coastal road infrastructure project in the Thane region.",
        "key_facts": ["Thane region", "Maharashtra coastal transport"],
        "official_source_url": "https://mmrda.maharashtra.gov.in/",
        "source_note": "Official Mumbai Metropolitan Region Development Authority source.",
        "tags": ["coastal-road", "maharashtra", "road"],
    },
    {
        "name": "Sela Tunnel",
        "category": "Tunnel",
        "location": "Tawang, Arunachal Pradesh",
        "status": "Completed",
        "description": "High-altitude tunnel project improving all-weather access toward Tawang.",
        "key_facts": ["Arunachal Pradesh", "High-altitude road connectivity"],
        "official_source_url": "https://www.bro.gov.in/",
        "source_note": "Official Border Roads Organisation source.",
        "tags": ["tunnel", "arunachal-pradesh", "bro"],
    },
    {
        "name": "Shinkun La Tunnel",
        "category": "Tunnel",
        "location": "Ladakh",
        "status": "Development / construction",
        "description": "Strategic high-altitude tunnel project in the Ladakh connectivity network.",
        "key_facts": ["Ladakh", "High-altitude connectivity"],
        "official_source_url": "https://www.bro.gov.in/",
        "source_note": "Official Border Roads Organisation source; status is intentionally kept at the broad development stage.",
        "tags": ["tunnel", "ladakh", "bro"],
    },
    {
        "name": "Bogibeel Bridge",
        "category": "Rail-road Bridge",
        "location": "Assam",
        "status": "Completed / operational",
        "description": "Combined rail and road bridge across the Brahmaputra in Assam.",
        "key_facts": ["Rail-road bridge", "Assam connectivity"],
        "official_source_url": "https://www.pib.gov.in/",
        "source_note": "Official Government of India source.",
        "tags": ["bridge", "rail", "road", "assam"],
    },
    {
        "name": "Dholera Semiconductor Projects",
        "category": "Semiconductor",
        "location": "Dholera, Gujarat",
        "status": "Under development",
        "description": "Semiconductor manufacturing and ecosystem projects being developed in the Dholera region.",
        "key_facts": ["Dholera Special Investment Region", "Semiconductor manufacturing ecosystem"],
        "official_source_url": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2252649",
        "source_note": "Status reviewed against an official semiconductor mission update.",
        "tags": ["semiconductor", "gujarat", "dholera"],
    },
    {
        "name": "Micron Semiconductor Facility",
        "category": "Semiconductor",
        "location": "Sanand, Gujarat",
        "status": "Under construction / development",
        "description": "Semiconductor assembly and test facility in Gujarat.",
        "key_facts": ["Sanand, Gujarat", "Semiconductor assembly and test"],
        "official_source_url": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2010132",
        "source_note": "Official Government of India source for approved semiconductor units.",
        "tags": ["semiconductor", "gujarat", "sanand"],
    },
    {
        "name": "Tata Semiconductor Facility",
        "category": "Semiconductor",
        "location": "Assam",
        "status": "Under development",
        "description": "Tata Electronics semiconductor facility in Assam.",
        "key_facts": ["Assam semiconductor manufacturing", "Tata Electronics project"],
        "official_source_url": "https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=2041162",
        "source_note": "Official Press Information Bureau source.",
        "tags": ["semiconductor", "assam"],
    },
    {
        "name": "Khavda Renewable Energy Park",
        "category": "Renewable Energy",
        "location": "Kutch, Gujarat",
        "status": "Ongoing development",
        "description": "Large renewable-energy development in the Khavda region of Gujarat.",
        "key_facts": ["Kutch region", "Renewable-energy infrastructure"],
        "official_source_url": "https://guj-nwrws.gujarat.gov.in/",
        "source_note": "Official Gujarat government source; no capacity or progress claims are included.",
        "tags": ["renewable-energy", "gujarat", "kutch"],
    },
    {
        "name": "AIIMS Gorakhpur",
        "category": "Hospital",
        "location": "Gorakhpur, Uttar Pradesh",
        "status": "Operational",
        "description": "Public medical institute and hospital serving eastern Uttar Pradesh.",
        "key_facts": ["Gorakhpur, Uttar Pradesh", "Medical institute and hospital"],
        "official_source_url": "https://aiimsgorakhpur.edu.in/",
        "source_note": "Official AIIMS Gorakhpur source.",
        "tags": ["hospital", "uttar-pradesh", "healthcare"],
    },
    {
        "name": "AIIMS Rae Bareli",
        "category": "Hospital",
        "location": "Rae Bareli, Uttar Pradesh",
        "status": "Operational",
        "description": "Public medical institute and hospital in Rae Bareli.",
        "key_facts": ["Rae Bareli, Uttar Pradesh", "Medical institute and hospital"],
        "official_source_url": "https://aiimsrbl.edu.in/",
        "source_note": "Official AIIMS Rae Bareli source.",
        "tags": ["hospital", "uttar-pradesh", "healthcare"],
    },
    {
        "name": "National Cancer Institute",
        "category": "Hospital",
        "location": "Jhajjar, Haryana",
        "status": "Operational",
        "description": "National cancer care institute at Jhajjar, Haryana.",
        "key_facts": ["Jhajjar, Haryana", "Cancer care infrastructure"],
        "official_source_url": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1566423",
        "source_note": "Official Government of India source.",
        "tags": ["hospital", "haryana", "healthcare"],
    },
    {
        "name": "New AIIMS campuses under PMSSY",
        "category": "Healthcare",
        "location": "Multiple states",
        "status": "Multiple stages",
        "description": "Grouped programme entry for new AIIMS campuses delivered through the Pradhan Mantri Swasthya Suraksha Yojana.",
        "key_facts": ["Grouped national programme", "Multiple campus locations"],
        "official_source_url": "https://pmssy.mohfw.gov.in/",
        "source_note": "Grouped programme entry; individual campus status is not collapsed into one invented project status.",
        "tags": ["healthcare", "multi-state", "pmssy"],
    },
    {
        "name": "Nalanda University Campus",
        "category": "University",
        "location": "Rajgir, Bihar",
        "status": "Operational",
        "description": "International university campus at Nalanda, Bihar.",
        "key_facts": ["Rajgir, Bihar", "International university campus"],
        "official_source_url": "https://nalandauniv.edu.in/",
        "source_note": "Official Nalanda University source.",
        "tags": ["education", "bihar", "university"],
    },
    {
        "name": "IIT/IIM new infrastructure projects",
        "category": "Education",
        "location": "Multiple states",
        "status": "Multiple stages",
        "description": "Grouped programme entry for new and expanded IIT and IIM infrastructure across India.",
        "key_facts": ["Grouped education programme", "Multiple campuses and packages"],
        "official_source_url": "https://www.education.gov.in/",
        "source_note": "Grouped programme entry; individual campus status is not represented as one physical project.",
        "tags": ["education", "multi-state", "iit", "iim"],
    },
    {
        "name": "Pradhanmantri Sangrahalaya",
        "category": "Museum",
        "location": "New Delhi",
        "status": "Operational",
        "description": "Museum and public history campus in New Delhi.",
        "key_facts": ["New Delhi", "Public history and museum campus"],
        "official_source_url": "https://www.pmml.nic.in/",
        "source_note": "Official museum and library source.",
        "tags": ["museum", "new-delhi", "heritage"],
    },
    {
        "name": "Ram Mandir complex and associated infrastructure",
        "category": "Heritage",
        "location": "Ayodhya, Uttar Pradesh",
        "status": "Ongoing development",
        "description": "Grouped heritage-campus and associated infrastructure entry for Ayodhya.",
        "key_facts": ["Ayodhya, Uttar Pradesh", "Heritage campus and visitor infrastructure"],
        "official_source_url": "https://srjbtkshetra.org/",
        "source_note": "Official Shri Ram Janmabhoomi Teerth Kshetra source; grouped entry avoids invented package-level progress.",
        "tags": ["heritage", "uttar-pradesh", "ayodhya"],
    },
    {
        "name": "Amrit Bharat Station redevelopment projects",
        "category": "Railway Stations",
        "location": "Across India",
        "status": "Under construction",
        "description": "Grouped programme entry for railway station redevelopment under the Amrit Bharat Station Scheme.",
        "key_facts": ["Grouped national programme", "Railway station redevelopment"],
        "official_source_url": "https://amritbharatstations.cris.org.in/",
        "source_note": "Grouped programme entry; individual station packages have separate schedules and statuses.",
        "tags": ["railway-stations", "rail", "multi-state"],
    },
    {
        "name": "Northeast connectivity projects",
        "category": "Roads / Bridges / Tunnels",
        "location": "Northeast India",
        "status": "Ongoing",
        "description": "Grouped regional connectivity entry covering road, bridge, and tunnel programmes in Northeast India.",
        "key_facts": ["Grouped regional programme", "Road, bridge, and tunnel connectivity"],
        "official_source_url": "https://mdoner.gov.in/",
        "source_note": "Grouped programme entry; individual packages require separate project-level verification.",
        "tags": ["roads", "bridges", "tunnels", "northeast-india"],
    },
]


def seed_india_projects():
    db = SessionLocal()
    try:
        existing_names = {row[0] for row in db.query(IndiaProject.name).all()}
        added = 0
        for item in INDIA_PROJECTS:
            if item["name"] in existing_names:
                continue
            db.add(IndiaProject(**item, last_verified_at=VERIFIED_AT))
            added += 1
        if added:
            db.commit()
        return added
    finally:
        db.close()